name: xport
description: A cli tool to export Apple provisioning profiles and signing certificates and upload them to GitHub Secrets.
version: 1.1.4
repository: https://github.com/Skycoder42/xport

environment:
  sdk: ^3.11.0

platforms:
  macos:

executables:
  xport:

dependencies:
  ansicolor: ^2.0.3
  args: ^2.7.0
  build_cli_annotations: ^2.1.1
  checked_yaml: ^2.0.4
  collection: ^1.19.1
  dio: ^5.9.1
  ffi: ^2.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  json_annotation: ^4.11.0
  logging: ^1.3.0
  meta: ^1.18.1
  objective_c: ^9.3.0
  path: ^1.9.1
  posix: ^6.5.0
  retrofit: ^4.9.2
  sodium: ^3.4.6
  yaml: ^3.1.3
  yaml_edit: ^2.2.4

dev_dependencies:
  build_cli: ^2.2.10
  build_runner: ^2.11.1
  dart_pre_commit: ^6.1.1+1
  dart_test_tools: ^7.0.2
  ffigen: ^20.1.1
  freezed: ^3.2.5
  injectable_generator: ^2.12.0
  json_serializable: ^6.13.0
  retrofit_generator: ^10.2.3

dart_pre_commit:
  flutter-compat: false
