name: xport
description: A cli tool to export Apple provisioning profiles and signing certificates and upload them to GitHub Secrets.
version: 1.1.3
repository: https://github.com/Skycoder42/xport

environment:
  sdk: ^3.10.0

platforms:
  macos:

executables:
  xport:

dependencies:
  ansicolor: ^2.0.3
  args: ^2.7.0
  build_cli_annotations: ^2.1.1
  checked_yaml: ^2.0.4
  collection: ^1.19.1
  dio: ^5.9.0
  ffi: ^2.1.4
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.17.0
  objective_c: ^9.2.1
  path: ^1.9.1
  posix: ^6.0.3
  retrofit: ^4.9.1
  sodium: ^3.4.6
  yaml: ^3.1.3
  yaml_edit: ^2.2.3

dev_dependencies:
  build_cli: ^2.2.8
  build_runner: ^2.10.4
  dart_pre_commit: ^6.1.0
  dart_test_tools: ^7.0.1
  ffigen: ^20.1.1
  freezed: ^3.2.3
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.0

dart_pre_commit:
  flutter-compat: false
