name: xport
description: A cli tool to export Apple provisioning profiles and signing certificates and upload them to GitHub Secrets.
version: 1.1.2
repository: https://github.com/Skycoder42/xport

environment:
  sdk: ^3.9.0

platforms:
  macos:

executables:
  xport:

dependencies:
  ansicolor: ^2.0.3
  args: ^2.7.0
  build_cli_annotations: ^2.1.1
  checked_yaml: ^2.0.4
  collection: ^1.19.1
  dio: ^5.9.0
  ffi: ^2.1.4
  freezed_annotation: ^3.1.0
  get_it: ">=8.3.0 <10.0.0"
  injectable: ^2.6.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  objective_c: ^9.0.0+1
  path: ^1.9.1
  posix: ^6.0.3
  retrofit: ^4.9.0
  sodium: ^3.4.6
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  build_cli: ^2.2.8
  build_runner: ^2.10.1
  custom_lint: ^0.8.1
  dart_pre_commit: ^6.0.0
  dart_test_tools: ">=6.2.3+1 <8.0.0"
  ffigen: ^20.0.0
  freezed: ^3.2.3
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.1
  retrofit_generator: ^10.1.4

dart_pre_commit:
  flutter-compat: false
