name: xport
description: A cli tool to export Apple provisioning profiles and signing certificates and upload them to GitHub Secrets.
version: 1.1.1
repository: https://github.com/Skycoder42/xport

environment:
  sdk: ^3.6.0

platforms:
  macos:

executables:
  xport:

dependencies:
  ansicolor: ^2.0.3
  args: ^2.6.0
  build_cli_annotations: ^2.1.0
  checked_yaml: ^2.0.3
  collection: ^1.19.1
  dio: ^5.7.0
  ffi: ^2.1.3
  freezed_annotation: ">=2.4.4 <4.0.0"
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  path: ^1.9.1
  posix: ^6.0.1
  retrofit: ^4.4.2
  sodium: ^3.4.4
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  build_cli: ^2.2.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  dart_pre_commit: ^5.4.2
  dart_test_tools: ^6.0.1
  ffigen: ">=16.0.0 <21.0.0"
  freezed: ">=2.5.7 <4.0.0"
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.7

dart_pre_commit:
  flutter-compat: false
