name: Automatic dependency updates

on:
  workflow_dispatch:
  schedule:
    - cron: "34 2 * * 3"

jobs:
  ci:
    name: Updates
    uses: Skycoder42/dart_test_tools/.github/workflows/auto-update.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      flutterCompat: false
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
